version: '3'
services:
    mongodb:
        image: mongo:3.6.5
        ports:
            - "27017:27017"
    redis:
        image: redis:4.0.10-alpine
        command: ["redis-server", "--appendonly", "yes", "--maxmemory", "1g"]
        ports:
            - "6379:6379"
