kind: ConfigMap
apiVersion: v1
metadata:
  namespace: tick
  name: influxdb
data:
  influxdb.conf: |+
    [meta]
      dir = "/var/lib/influxdb/meta"
      retention-autocreate = false
    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      index-version = "tsi1"
  init.iql: |+
    CREATE DATABASE "nodes" WITH DURATION 90d REPLICATION 1 SHARD DURATION 1h NAME "rp_90d"
