kind: Service
apiVersion: v1
metadata:
  name: simple-api
  labels:
    app: simple-api
spec:
  type: NodePort
  selector:
    app: simple-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
