kind: Service
apiVersion: v1
metadata:
  name: simple-frontend
  labels:
    app: simple-frontend
spec:
  type: NodePort
  selector:
    app: simple-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
