kind: Deployment
apiVersion: apps/v1
metadata:
  name: simple-frontend
  labels:
    app: simple-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-frontend
  template:
    metadata:
      labels:
        app: simple-frontend
    spec:
      containers:
      - name: simple-frontend
        image: asia.gcr.io/simple-project-198818/simple-frontend:4fc4199
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 100M
          limits:
            cpu: 100m
            memory: 100M
        livenessProbe:
          httpGet:
            path: /
            port: 80
